#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9631FEAF0CC6227 (infra-root@openstack.org)
#
Name     : glance_store
Version  : 0.18.0
Release  : 41
URL      : http://tarballs.openstack.org/glance_store/glance_store-0.18.0.tar.gz
Source0  : http://tarballs.openstack.org/glance_store/glance_store-0.18.0.tar.gz
Source99 : http://tarballs.openstack.org/glance_store/glance_store-0.18.0.tar.gz.asc
Summary  : OpenStack Image Service Store Library
Group    : Development/Tools
License  : Apache-2.0
Requires: glance_store-bin
Requires: glance_store-python
Requires: debtcollector
Requires: enum34
Requires: eventlet
Requires: httplib2
Requires: jsonschema
Requires: os-brick
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.rootwrap
Requires: oslo.serialization
Requires: oslo.utils
Requires: oslo.vmware
Requires: python-cinderclient
Requires: python-keystoneclient
Requires: python-swiftclient
Requires: requests
Requires: six
Requires: stevedore
BuildRequires : configparser-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Glance Store Library
=====================
Glance's stores library
* License: Apache License, Version 2.0
* Documentation: http://docs.openstack.org/developer/glance_store
* Source: http://git.openstack.org/cgit/openstack/glance_store
* Bugs: http://bugs.launchpad.net/glance-store

%package bin
Summary: bin components for the glance_store package.
Group: Binaries

%description bin
bin components for the glance_store package.


%package python
Summary: python components for the glance_store package.
Group: Default

%description python
python components for the glance_store package.


%prep
%setup -q -n glance_store-0.18.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489281518
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489281518
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/glance-rootwrap

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
