#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : glance_store
Version  : 0.26.1
Release  : 45
URL      : http://tarballs.openstack.org/glance_store/glance_store-0.26.1.tar.gz
Source0  : http://tarballs.openstack.org/glance_store/glance_store-0.26.1.tar.gz
Source99 : http://tarballs.openstack.org/glance_store/glance_store-0.26.1.tar.gz.asc
Summary  : OpenStack Image Service Store Library
Group    : Development/Tools
License  : Apache-2.0
Requires: glance_store-bin
Requires: glance_store-python3
Requires: glance_store-license
Requires: glance_store-python
Requires: Sphinx
Requires: bandit
Requires: coverage
Requires: doc8
Requires: enum34
Requires: eventlet
Requires: fixtures
Requires: hacking
Requires: httplib2
Requires: jsonschema
Requires: keystoneauth1
Requires: openstackdocstheme
Requires: os-brick
Requires: os-testr
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.rootwrap
Requires: oslo.serialization
Requires: oslo.utils
Requires: oslo.vmware
Requires: oslotest
Requires: python-cinderclient
Requires: python-keystoneclient
Requires: python-mock
Requires: python-subunit
Requires: python-swiftclient
Requires: reno
Requires: requests
Requires: requests-mock
Requires: six
Requires: stevedore
Requires: testscenarios
Requires: testtools
BuildRequires : buildreq-distutils3
BuildRequires : pbr

%description
Team and repository tags
        ========================

%package bin
Summary: bin components for the glance_store package.
Group: Binaries
Requires: glance_store-license

%description bin
bin components for the glance_store package.


%package license
Summary: license components for the glance_store package.
Group: Default

%description license
license components for the glance_store package.


%package python
Summary: python components for the glance_store package.
Group: Default
Requires: glance_store-python3

%description python
python components for the glance_store package.


%package python3
Summary: python3 components for the glance_store package.
Group: Default
Requires: python3-core

%description python3
python3 components for the glance_store package.


%prep
%setup -q -n glance_store-0.26.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533088462
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/glance_store
cp LICENSE %{buildroot}/usr/share/doc/glance_store/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/glance-rootwrap

%files license
%defattr(-,root,root,-)
/usr/share/doc/glance_store/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
